import os
import requests
import json
from pathlib import Path
from utils.helpers import setup_logger
from ai_engine.ollama_client import OllamaClient

logger = setup_logger("WebResearcher")

class WebResearcher:
    def __init__(self):
        self.ai = OllamaClient()

    def research_topic(self, topic: str) -> str:
        """
        Uses DuckDuckGo HTML Lite to search for a topic, scrape top text,
        then uses Ollama to summarize it into a Desktop report.
        """
        try:
            logger.info(f"Starting research on: {topic}")
            url = f"https://html.duckduckgo.com/html/?q={topic.replace(' ', '+')}"
            headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"}
            
            resp = requests.get(url, headers=headers, timeout=10)
            if resp.status_code != 200:
                return "Failed to reach search engine."

            # Very basic extraction to avoid heavy dependencies like BeautifulSoup
            # We'll extract text within <a class="result__snippet">
            snippets = []
            html = resp.text
            parts = html.split('class="result__snippet')
            for p in parts[1:6]:  # Top 5 results
                try:
                    snippet = p.split('>')[1].split('<')[0]
                    snippets.append(snippet)
                except:
                    pass

            raw_text = " ".join(snippets)
            if not raw_text.strip():
                return "Could not find reliable information on that topic."

            # Summarize using AI
            prompt = f"Summarize this research material about '{topic}':\n\n{raw_text}\n\nProvide a clean, bulleted summary."
            summary = self.ai.generate(prompt=prompt, system_prompt="You are an expert researcher. Be concise and informative.")

            if summary.startswith("Error"):
                return summary

            # Save report to desktop
            desktop = Path(os.path.expanduser("~/Desktop"))
            filename = f"Research_Report_{topic.replace(' ', '_')[:20]}.md"
            filepath = desktop / filename

            with open(filepath, "w", encoding="utf-8") as f:
                f.write(f"# Research Report: {topic}\n\n{summary}\n\n*Generated by AURA*")

            logger.info(f"Report saved to {filepath}")
            return f"Research complete. I have saved a report to your Desktop: {filename}"

        except Exception as e:
            logger.error(f"Research error: {e}")
            return f"Research failed: {str(e)}"
